services:

  postgres:
    image: postgres:16

    container_name: dentist-postgres

    environment:
      POSTGRES_DB: dentistdb
      POSTGRES_USER: dentist
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dentist -d dentistdb"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always



  backend:
    build:
      context: ./backend

    container_name: dentist-backend

    ports:
      - "7166:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    restart: always



  frontend:
    build:
      context: ./dentist-frontend

    container_name: dentist-frontend

    ports:
      - "3000:3000"

    depends_on:
      backend:
        condition: service_started

    restart: always



volumes:

  postgres_data: